name: PR Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check file changes and added lines
        id: pr_stats
        run: |
          changes=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" \
            | jq '.[] | select(.status != "removed")')
          echo "::set-output name=changes::$changes"
        
      - name: Refuse PR
        uses: actions/github-script@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            sudo apt update
            sudo apt install curl
            sudo apt install jq
            pr_files=$(jq -r '.pull_request.files' "$GITHUB_EVENT_PATH")
            totalFileChanges=0
            totalAddedLines=0

            for file in $pr_files; do
            totalFileChanges=$((totalFileChanges + 1))
            additions=$(jq -r ".additions" <<< "$file")
            totalAddedLines=$((totalAddedLines + additions))
            done

            if (( totalFileChanges > 1 || totalAddedLines > 1 )); then
            prNumber=$(jq -r '.number' "$GITHUB_EVENT_PATH")
            owner=$(jq -r '.repository.owner.login' "$GITHUB_EVENT_PATH")
            repo=$(jq -r '.repository.name' "$GITHUB_EVENT_PATH")
            comment="Sorry, your pull request exceeds the file changes and added lines limit. Please make sure your changes comply with our guidelines."

            body="{ \"owner\": \"$owner\", \"repo\": \"$repo\", \"issue_number\": $prNumber, \"body\": \"$comment\" }"
            curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" -H "Content-Type: application/json" -d "$body" "https://api.github.com/repos/$owner/$repo/issues/$prNumber/comments"

            declineBody="{ \"owner\": \"$owner\", \"repo\": \"$repo\", \"pull_number\": $prNumber, \"state\": \"closed\" }"
            curl -X PATCH -H "Authorization: Bearer $GITHUB_TOKEN" -H "Content-Type: application/json" -d "$declineBody" "https://api.github.com/repos/$owner/$repo/pulls/$prNumber"
            fi
