name: Auto PR Review

on:
  pull_request:
    types:
      - opened

jobs:
  pull-request-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check file changes limit
        run: |
          changed_files=$(git diff --name-only HEAD^)
          file_changes_limit=1
          if [ $(echo "$changed_files" | wc -l) -gt $file_changes_limit ]; then
            echo "::error::This PR exceeds the file changes limit ($file_changes_limit files)."
            exit 1
          fi


      - name: Refuse the pull request
        run: |
          pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          github_token=${{ secrets.GITHUB_TOKEN }}
          curl -X POST \
            -H "Authorization: token $github_token" \
            -H "Content-Type: application/json" \
            -d '{"body": "This pull request does not meet the criteria."}' \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$pr_number/comments"
          echo "::set-output name=refused::true"

      - name: Notify refusal in a PR comment
        if: steps.refuse.outputs.refused == 'true'
        run: echo "This pull request has been refused."
