name: Example workflow

on:
  pull_request:
    types: [opened, synchronize]
   
 
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codee
        uses: actions/checkout@v2
      - name: Get base branch name
        run: echo "Base branch name is ${{ github.base_ref }}"
      - name: fetch origin 
        run: git fetch origin
      - name: Get head branch name
        run: echo "Head branch name is ${{ github.head_ref }}"\
      - name: Get branch name
        run: git branch -a
      - name: Get current branch name
        run: echo "${GITHUB_REF#refs/heads/}"
      - name: Count modified files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            MODIFIED_FILES=$(git diff origin/master origin/dev --name-only)
            FILE_COUNT=$(echo "$MODIFIED_FILES" | wc -l)
            echo "$FILE_COUNT"
            if [ "&FILE_COUNT" -gt 2 ]; then
            COMMENT_BODY="🚫 This pull request has been automatically rejected because it modifies more than one file."
            curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\": \"$COMMENT_BODY\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
            else
            COMMENT_BODY="This pull request has been automatically approved ."
            curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\": \"$COMMENT_BODY\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
            fi
            
