name: Pull Request Limit

on:
  pull_request:
    branches:
      - dev
      - main
    types:
      - opened
      - synchronize
      
jobs:
  check_changes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Count file changes
        id: count
        run: echo "::set-output name=changes::$(git diff --numstat ${{ github.base_ref }}...${{ github.head_ref }} | wc -l)"
        
      - name: Refuse pull request
        if: ${{ steps.count.outputs.changes > 1 }}
        run: |
          echo "Pull request exceeds the limit of 10 file changes"
          exit 1
