name: PR Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check file changes and added lines
        id: pr_stats
        uses: andstor/file-changes-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          creator: ${{ github.actor }}
          pr_head_sha: ${{ github.event.pull_request.head.sha }}

      - name: Refuse PR
        uses: actions/github-script@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const totalFileChanges = ${{ steps.pr_stats.outputs.files_changed }};
            const totalAddedLines = ${{ steps.pr_stats.outputs.additions }};

            if (totalFileChanges > 10 || totalAddedLines > 100) {
              const prNumber = context.payload.pull_request.number;
              const owner = context.payload.repository.owner.login;
              const repo = context.payload.repository.name;
              const comment = `Sorry, your pull request exceeds the file changes and added lines limit. Please make sure your changes comply with our guidelines.`;

              const body = {
                owner: owner,
                repo: repo,
                issue_number: prNumber,
                body: comment
              };

              await github.issues.createComment(body);

              const declineBody = {
                owner: owner,
                repo: repo,
                pull_number: prNumber
              };

              await github.pulls.update(declineBody);
            }

