name: Refuse PR

on:
  pull_request:

jobs:
  name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        run: git diff --name-only HEAD HEAD~1 > changed_files.txt

      - name: Count changed files
        run: cat changed_files.txt | wc -l > num_changed_files.txt

      - name: Get number of added lines
        run: git diff --numstat HEAD HEAD~1 > numstat.txt

      - name: Count added lines
        run: grep '+' numstat.txt | awk '{s+=$1} END {print s}' > num_added_lines.txt

      - name: Check if number of changed files is greater than limit
        run: |
          if [ $(cat num_changed_files.txt) -gt 1 ]; then
            echo 'Number of changed files is greater than limit'
            exit 1
          fi

      - name: Check if number of added lines is greater than limit
        run: |
          if [ $(cat num_added_lines.txt) -gt 1 ]; then
            echo 'Number of added lines is greater than limit'
            exit 1
          fi

      - name: Refuse pull request
        uses: actions/github-script@v5
        with:
          script: |
              github.issues.createComment({
              issue_number: context.issue.number,
              body: 'Pull request refused due to too many changed files or added lines.'
              })
              """
