name: Pull Request Rules

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pull_request_rules:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Check Pull Request Conditions
        run: |

          changed_files=$(git diff --name-only HEAD^)
          file_changes_limit=1
          if [ $(echo "$changed_files" | wc -l) -gt $file_changes_limit ]; then
            echo "::error::This PR exceeds the file changes limit ($file_changes_limit files)."
            exit 1
          fi


      - name: Refuse the pull request
        run: |
          pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          github_token=${{ secrets.GITHUB_TOKEN }}
          curl -X POST \
            -H "Authorization: token $github_token" \
            -H "Content-Type: application/json" \
            -d '{"body": "This pull request does not meet the criteria."}' \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$pr_number/comments"
          echo "::set-output name=refused::true"

      - name: Notify refusal in a PR comment
        if: steps.refuse.outputs.refused == 'true'
        run: echo "This pull request has been refused."
          # Limit the number of file changes
          FILE_CHANGES=$(git diff --name-only --root HEAD | wc -l)
          if [[ "$FILE_CHANGES" -gt 1 ]]; then
            echo "🛑 Error: The number of file changes exceeds the limit."
            exit 1
          fi
          
          # If no conditions are violated, the script will exit successfully.
      
      - name: Refuse Pull Request
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/issues/{issue_number}/comments
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.pull_request.head.repo.name }}
          issue_number: ${{ github.event.pull_request.number }}
          body: |
            ⛔️ This pull request violates the rules. Please check the guidelines and make the necessary changes.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
