name: Pull Request Rules

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pull_request_rules:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Check Pull Request Conditions
        run: |
           exit 1
           echo " no pull request "

  
          # If no conditions are violated, the script will exit successfully.
      
      - name: Refuse Pull Request
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/issues/{issue_number}/comments
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.pull_request.head.repo.name }}
          issue_number: ${{ github.event.pull_request.number }}
          body: |
            ⛔️ This pull request violates the rules. Please check the guidelines and make the necessary changes.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
